# The name of the organisation or entity that owns this project
organisation: "Raymond Lee"

# A live web address for the organisation
url: "http://ebw.co/template"

# The default contact email address
email: "rlee@heimagongsi.org"

# The name of the project of books in this folder.
name: "Classic Chinese Translations"

# A one-liner about this project. Useful for Open Graph metadata.
description: "This is a repository of my English translations of Classic Chinese Texts using the Electric Book template. Created and maintained by Raymond Lee."

# The logo of the organisation, saved web-ready in /assets
logo: "logo.svg"

# An image in /assets/images/web that stands for the project
image: "cover.jpg"

# Credit line, by default in the footer, overidden in locales.yml
credit: "Built with the [Electric Book template](https://ebw.co/template)."

# Primary language code for this project as a whole
language: "en"

# App bundle ID unique across all app stores
app-id: com.example.myapp

# Version. You must change this with each app update
version: "1.0.0"
